/**
 * Item Seed Script
 * Run: node seeds/seedItems.js
 * Populates the items table with tradeable items for all SoulsBorne games.
 */

require('dotenv').config({ path: require('path').join(__dirname, '..', '.env') });
const { sequelize, Item } = require('../models');

const ITEMS = [

  // ═══════════════════════════════════════════
  //  DARK SOULS (Remastered)
  // ═══════════════════════════════════════════

  // Weapons
  { game: 'Dark Souls', type: 'weapon', name: 'Longsword' },
  { game: 'Dark Souls', type: 'weapon', name: 'Claymore' },
  { game: 'Dark Souls', type: 'weapon', name: 'Bastard Sword' },
  { game: 'Dark Souls', type: 'weapon', name: 'Zweihander' },
  { game: 'Dark Souls', type: 'weapon', name: 'Uchigatana' },
  { game: 'Dark Souls', type: 'weapon', name: 'Washing Pole' },
  { game: 'Dark Souls', type: 'weapon', name: 'Black Knight Sword' },
  { game: 'Dark Souls', type: 'weapon', name: 'Black Knight Greataxe' },
  { game: 'Dark Souls', type: 'weapon', name: 'Black Knight Halberd' },
  { game: 'Dark Souls', type: 'weapon', name: 'Chaos Blade' },
  { game: 'Dark Souls', type: 'weapon', name: 'Moonlight Greatsword' },
  { game: 'Dark Souls', type: 'weapon', name: 'Drake Sword' },
  { game: 'Dark Souls', type: 'weapon', name: 'Sunlight Straight Sword' },
  { game: 'Dark Souls', type: 'weapon', name: 'Balder Side Sword' },
  { game: 'Dark Souls', type: 'weapon', name: 'Silver Knight Straight Sword' },
  { game: 'Dark Souls', type: 'weapon', name: 'Man-Serpent Greatsword' },
  { game: 'Dark Souls', type: 'weapon', name: "Demon's Greataxe" },
  { game: 'Dark Souls', type: 'weapon', name: 'Gravelord Sword' },
  { game: 'Dark Souls', type: 'weapon', name: 'Lifehunt Scythe' },
  { game: 'Dark Souls', type: 'weapon', name: 'Estoc' },
  { game: 'Dark Souls', type: 'weapon', name: "Ricard's Rapier" },
  { game: 'Dark Souls', type: 'weapon', name: 'Titanite Catch Pole' },
  { game: 'Dark Souls', type: 'weapon', name: 'Painting Guardian Sword' },
  { game: 'Dark Souls', type: 'weapon', name: 'Ghost Blade' },
  { game: 'Dark Souls', type: 'weapon', name: 'Gargoyle Tail Axe' },
  { game: 'Dark Souls', type: 'weapon', name: 'Quelaag\'s Furysword' },
  { game: 'Dark Souls', type: 'weapon', name: "Priscilla's Dagger" },
  { game: 'Dark Souls', type: 'weapon', name: 'Great Scythe' },
  { game: 'Dark Souls', type: 'weapon', name: 'Iaito' },
  { game: 'Dark Souls', type: 'weapon', name: 'Murakumo' },
  // Shields
  { game: 'Dark Souls', type: 'shield', name: 'Grass Crest Shield' },
  { game: 'Dark Souls', type: 'shield', name: 'Eagle Shield' },
  { game: 'Dark Souls', type: 'shield', name: 'Black Iron Greatshield' },
  { game: 'Dark Souls', type: 'shield', name: "Havel's Greatshield" },
  { game: 'Dark Souls', type: 'shield', name: 'Crest Shield' },
  { game: 'Dark Souls', type: 'shield', name: 'Crystal Shield' },
  { game: 'Dark Souls', type: 'shield', name: 'Tower Kite Shield' },
  { game: 'Dark Souls', type: 'shield', name: 'Heater Shield' },
  // Armor
  { game: 'Dark Souls', type: 'armor', name: 'Elite Knight Helm' },
  { game: 'Dark Souls', type: 'armor', name: 'Elite Knight Armor' },
  { game: 'Dark Souls', type: 'armor', name: 'Elite Knight Gauntlets' },
  { game: 'Dark Souls', type: 'armor', name: 'Elite Knight Leggings' },
  { game: 'Dark Souls', type: 'armor', name: "Havel's Helm" },
  { game: 'Dark Souls', type: 'armor', name: "Havel's Armor" },
  { game: 'Dark Souls', type: 'armor', name: "Havel's Gauntlets" },
  { game: 'Dark Souls', type: 'armor', name: "Havel's Leggings" },
  { game: 'Dark Souls', type: 'armor', name: "Artorias's Helm" },
  { game: 'Dark Souls', type: 'armor', name: "Artorias's Armor" },
  { game: 'Dark Souls', type: 'armor', name: "Artorias's Gauntlets" },
  { game: 'Dark Souls', type: 'armor', name: "Artorias's Leggings" },
  { game: 'Dark Souls', type: 'armor', name: "Ornstein's Helm" },
  { game: 'Dark Souls', type: 'armor', name: "Ornstein's Armor" },
  { game: 'Dark Souls', type: 'armor', name: "Ornstein's Gauntlets" },
  { game: 'Dark Souls', type: 'armor', name: "Ornstein's Leggings" },
  { game: 'Dark Souls', type: 'armor', name: "Smough's Helm" },
  { game: 'Dark Souls', type: 'armor', name: "Smough's Armor" },
  { game: 'Dark Souls', type: 'armor', name: "Smough's Gauntlets" },
  { game: 'Dark Souls', type: 'armor', name: "Smough's Leggings" },
  { game: 'Dark Souls', type: 'armor', name: 'Silver Knight Helm' },
  { game: 'Dark Souls', type: 'armor', name: 'Silver Knight Armor' },
  { game: 'Dark Souls', type: 'armor', name: 'Silver Knight Gauntlets' },
  { game: 'Dark Souls', type: 'armor', name: 'Silver Knight Leggings' },
  // Consumables / Materials
  { game: 'Dark Souls', type: 'consumable', name: 'Humanity' },
  { game: 'Dark Souls', type: 'consumable', name: 'Twin Humanities' },
  { game: 'Dark Souls', type: 'consumable', name: 'Titanite Shard' },
  { game: 'Dark Souls', type: 'consumable', name: 'Large Titanite Shard' },
  { game: 'Dark Souls', type: 'consumable', name: 'Titanite Chunk' },
  { game: 'Dark Souls', type: 'consumable', name: 'Titanite Slab' },
  { game: 'Dark Souls', type: 'consumable', name: 'Twinkling Titanite' },
  { game: 'Dark Souls', type: 'consumable', name: 'Demon Titanite' },
  { game: 'Dark Souls', type: 'consumable', name: 'Dragon Scale' },
  { game: 'Dark Souls', type: 'consumable', name: 'Green Titanite Shard' },
  { game: 'Dark Souls', type: 'consumable', name: 'White Titanite Shard' },
  { game: 'Dark Souls', type: 'consumable', name: 'Blue Titanite Shard' },
  { game: 'Dark Souls', type: 'consumable', name: 'Red Titanite Shard' },
  { game: 'Dark Souls', type: 'consumable', name: 'Green Titanite Chunk' },
  { game: 'Dark Souls', type: 'consumable', name: 'White Titanite Chunk' },
  { game: 'Dark Souls', type: 'consumable', name: 'Blue Titanite Chunk' },
  { game: 'Dark Souls', type: 'consumable', name: 'Red Titanite Chunk' },
  { game: 'Dark Souls', type: 'consumable', name: "Elizabeth's Mushroom" },
  { game: 'Dark Souls', type: 'consumable', name: 'Divine Blessing' },
  { game: 'Dark Souls', type: 'consumable', name: 'Transient Curse' },
  { game: 'Dark Souls', type: 'consumable', name: 'Black Firebomb' },
  { game: 'Dark Souls', type: 'consumable', name: "Lloyd's Talisman" },
  { game: 'Dark Souls', type: 'consumable', name: 'Cracked Red Eye Orb' },
  { game: 'Dark Souls', type: 'consumable', name: 'Eye of Death' },
  { game: 'Dark Souls', type: 'consumable', name: 'Souvenir of Reprisal' },
  { game: 'Dark Souls', type: 'consumable', name: 'Sunlight Medal' },
  // Rings
  { game: 'Dark Souls', type: 'ring', name: "Havel's Ring" },
  { game: 'Dark Souls', type: 'ring', name: 'Ring of Favor and Protection' },
  { game: 'Dark Souls', type: 'ring', name: 'Wolf Ring' },
  { game: 'Dark Souls', type: 'ring', name: 'Hawk Ring' },
  { game: 'Dark Souls', type: 'ring', name: 'Leo Ring' },
  { game: 'Dark Souls', type: 'ring', name: 'Hornet Ring' },
  { game: 'Dark Souls', type: 'ring', name: 'Covetous Gold Serpent Ring' },
  { game: 'Dark Souls', type: 'ring', name: 'Covetous Silver Serpent Ring' },
  { game: 'Dark Souls', type: 'ring', name: 'Orange Charred Ring' },
  { game: 'Dark Souls', type: 'ring', name: 'Ring of Sacrifice' },
  { game: 'Dark Souls', type: 'ring', name: 'Rare Ring of Sacrifice' },
  { game: 'Dark Souls', type: 'ring', name: 'Tiny Being\'s Ring' },
  { game: 'Dark Souls', type: 'ring', name: 'Lingering Dragoncrest Ring' },
  { game: 'Dark Souls', type: 'ring', name: 'Slumbering Dragoncrest Ring' },
  { game: 'Dark Souls', type: 'ring', name: 'Ring of the Sun\'s Firstborn' },
  { game: 'Dark Souls', type: 'ring', name: 'Covenant of Artorias' },
  { game: 'Dark Souls', type: 'ring', name: 'Calamity Ring' },
  { game: 'Dark Souls', type: 'ring', name: 'Cat Covenant Ring' },

  // ═══════════════════════════════════════════
  //  DARK SOULS 2
  // ═══════════════════════════════════════════

  { game: 'Dark Souls 2', type: 'weapon', name: 'Defender Greatsword' },
  { game: 'Dark Souls 2', type: 'weapon', name: 'Watcher Greatsword' },
  { game: 'Dark Souls 2', type: 'weapon', name: 'Puzzling Stone Sword' },
  { game: 'Dark Souls 2', type: 'weapon', name: 'Blue Flame' },
  { game: 'Dark Souls 2', type: 'weapon', name: 'Fume Ultra Greatsword' },
  { game: 'Dark Souls 2', type: 'weapon', name: 'Crypt Blacksword' },
  { game: 'Dark Souls 2', type: 'weapon', name: 'Black Knight Ultra Greatsword' },
  { game: 'Dark Souls 2', type: 'weapon', name: 'Aged Smelter Sword' },
  { game: 'Dark Souls 2', type: 'weapon', name: 'Sacred Chime Hammer' },
  { game: 'Dark Souls 2', type: 'weapon', name: 'King\'s Ultra Greatsword' },
  { game: 'Dark Souls 2', type: 'weapon', name: 'Warped Sword' },
  { game: 'Dark Souls 2', type: 'weapon', name: 'Curved Nil Greatsword' },
  { game: 'Dark Souls 2', type: 'weapon', name: 'Espada Ropera' },
  { game: 'Dark Souls 2', type: 'weapon', name: 'Chaos Blade' },
  { game: 'Dark Souls 2', type: 'weapon', name: 'Bewitched Alonne Sword' },
  { game: 'Dark Souls 2', type: 'shield', name: 'Rebel\'s Greatshield' },
  { game: 'Dark Souls 2', type: 'shield', name: 'Dragonrider Greatshield' },
  { game: 'Dark Souls 2', type: 'shield', name: 'Havel\'s Greatshield' },
  { game: 'Dark Souls 2', type: 'armor', name: 'Velstadt\'s Helm' },
  { game: 'Dark Souls 2', type: 'armor', name: 'Velstadt\'s Armor' },
  { game: 'Dark Souls 2', type: 'armor', name: 'Velstadt\'s Gauntlets' },
  { game: 'Dark Souls 2', type: 'armor', name: 'Velstadt\'s Leggings' },
  { game: 'Dark Souls 2', type: 'armor', name: 'Havel\'s Helm' },
  { game: 'Dark Souls 2', type: 'armor', name: 'Havel\'s Armor' },
  { game: 'Dark Souls 2', type: 'armor', name: 'Havel\'s Gauntlets' },
  { game: 'Dark Souls 2', type: 'armor', name: 'Havel\'s Leggings' },
  { game: 'Dark Souls 2', type: 'consumable', name: 'Titanite Shard' },
  { game: 'Dark Souls 2', type: 'consumable', name: 'Large Titanite Shard' },
  { game: 'Dark Souls 2', type: 'consumable', name: 'Titanite Chunk' },
  { game: 'Dark Souls 2', type: 'consumable', name: 'Titanite Slab' },
  { game: 'Dark Souls 2', type: 'consumable', name: 'Twinkling Titanite' },
  { game: 'Dark Souls 2', type: 'consumable', name: 'Petrified Dragon Bone' },
  { game: 'Dark Souls 2', type: 'consumable', name: 'Bonfire Ascetic' },
  { game: 'Dark Souls 2', type: 'consumable', name: 'Human Effigy' },
  { game: 'Dark Souls 2', type: 'consumable', name: 'Smooth & Silky Stone' },
  { game: 'Dark Souls 2', type: 'consumable', name: 'Sunlight Medal' },
  { game: 'Dark Souls 2', type: 'consumable', name: 'Token of Fidelity' },
  { game: 'Dark Souls 2', type: 'consumable', name: 'Token of Spite' },
  { game: 'Dark Souls 2', type: 'ring', name: 'Ring of Blades' },
  { game: 'Dark Souls 2', type: 'ring', name: 'Chloranthy Ring' },
  { game: 'Dark Souls 2', type: 'ring', name: 'Havel\'s Ring' },
  { game: 'Dark Souls 2', type: 'ring', name: 'Third Dragon Ring' },
  { game: 'Dark Souls 2', type: 'ring', name: 'Stone Ring' },
  { game: 'Dark Souls 2', type: 'ring', name: 'Ring of Soul Protection' },
  { game: 'Dark Souls 2', type: 'ring', name: 'Covetous Gold Serpent Ring' },

  // ═══════════════════════════════════════════
  //  DARK SOULS 3
  // ═══════════════════════════════════════════

  { game: 'Dark Souls 3', type: 'weapon', name: 'Lothric Knight Sword' },
  { game: 'Dark Souls 3', type: 'weapon', name: 'Dark Sword' },
  { game: 'Dark Souls 3', type: 'weapon', name: 'Farron Greatsword' },
  { game: 'Dark Souls 3', type: 'weapon', name: 'Hollowslayer Greatsword' },
  { game: 'Dark Souls 3', type: 'weapon', name: 'Exile Greatsword' },
  { game: 'Dark Souls 3', type: 'weapon', name: 'Wolf Knight\'s Greatsword' },
  { game: 'Dark Souls 3', type: 'weapon', name: 'Profaned Greatsword' },
  { game: 'Dark Souls 3', type: 'weapon', name: 'Greatsword of Judgment' },
  { game: 'Dark Souls 3', type: 'weapon', name: 'Firelink Greatsword' },
  { game: 'Dark Souls 3', type: 'weapon', name: 'Dragonslayer Greataxe' },
  { game: 'Dark Souls 3', type: 'weapon', name: 'Gundyr\'s Halberd' },
  { game: 'Dark Souls 3', type: 'weapon', name: 'Dragonslayer Spear' },
  { game: 'Dark Souls 3', type: 'weapon', name: 'Friede\'s Great Scythe' },
  { game: 'Dark Souls 3', type: 'weapon', name: 'Crucifix of the Mad King' },
  { game: 'Dark Souls 3', type: 'weapon', name: 'Crow Quills' },
  { game: 'Dark Souls 3', type: 'weapon', name: 'Onikiri and Ubadachi' },
  { game: 'Dark Souls 3', type: 'weapon', name: 'Chaos Blade' },
  { game: 'Dark Souls 3', type: 'weapon', name: 'Moonlight Greatsword' },
  { game: 'Dark Souls 3', type: 'weapon', name: 'Ringed Knight Paired Greatswords' },
  { game: 'Dark Souls 3', type: 'weapon', name: 'Frayed Blade' },
  { game: 'Dark Souls 3', type: 'shield', name: 'Lothric Knight Shield' },
  { game: 'Dark Souls 3', type: 'shield', name: 'Dragon Crest Shield' },
  { game: 'Dark Souls 3', type: 'shield', name: 'Dragonslayer Greatshield' },
  { game: 'Dark Souls 3', type: 'armor', name: 'Lothric Knight Helm' },
  { game: 'Dark Souls 3', type: 'armor', name: 'Lothric Knight Armor' },
  { game: 'Dark Souls 3', type: 'armor', name: 'Lothric Knight Gauntlets' },
  { game: 'Dark Souls 3', type: 'armor', name: 'Lothric Knight Leggings' },
  { game: 'Dark Souls 3', type: 'armor', name: 'Dancer\'s Crown' },
  { game: 'Dark Souls 3', type: 'armor', name: 'Dancer\'s Armor' },
  { game: 'Dark Souls 3', type: 'armor', name: 'Dancer\'s Gauntlets' },
  { game: 'Dark Souls 3', type: 'armor', name: 'Dancer\'s Leggings' },
  { game: 'Dark Souls 3', type: 'armor', name: 'Black Hand Armor' },
  { game: 'Dark Souls 3', type: 'consumable', name: 'Titanite Shard' },
  { game: 'Dark Souls 3', type: 'consumable', name: 'Large Titanite Shard' },
  { game: 'Dark Souls 3', type: 'consumable', name: 'Titanite Chunk' },
  { game: 'Dark Souls 3', type: 'consumable', name: 'Titanite Slab' },
  { game: 'Dark Souls 3', type: 'consumable', name: 'Twinkling Titanite' },
  { game: 'Dark Souls 3', type: 'consumable', name: 'Titanite Scale' },
  { game: 'Dark Souls 3', type: 'consumable', name: 'Sunlight Medal' },
  { game: 'Dark Souls 3', type: 'consumable', name: 'Pale Tongue' },
  { game: 'Dark Souls 3', type: 'consumable', name: 'Vertebra Shackle' },
  { game: 'Dark Souls 3', type: 'consumable', name: 'Proof of a Concord Kept' },
  { game: 'Dark Souls 3', type: 'consumable', name: 'Archtree Fragment' },
  { game: 'Dark Souls 3', type: 'ring', name: 'Havel\'s Ring' },
  { game: 'Dark Souls 3', type: 'ring', name: 'Ring of Favor' },
  { game: 'Dark Souls 3', type: 'ring', name: 'Chloranthy Ring' },
  { game: 'Dark Souls 3', type: 'ring', name: 'Lloyd\'s Sword Ring' },
  { game: 'Dark Souls 3', type: 'ring', name: 'Covetous Silver Serpent Ring' },
  { game: 'Dark Souls 3', type: 'ring', name: 'Covetous Gold Serpent Ring' },
  { game: 'Dark Souls 3', type: 'ring', name: 'Ring of Steel Protection' },

  // ═══════════════════════════════════════════
  //  ELDEN RING
  // ═══════════════════════════════════════════

  { game: 'Elden Ring', type: 'weapon', name: 'Moonveil' },
  { game: 'Elden Ring', type: 'weapon', name: 'Rivers of Blood' },
  { game: 'Elden Ring', type: 'weapon', name: 'Blasphemous Blade' },
  { game: 'Elden Ring', type: 'weapon', name: 'Dark Moon Greatsword' },
  { game: 'Elden Ring', type: 'weapon', name: 'Starscourge Greatsword' },
  { game: 'Elden Ring', type: 'weapon', name: 'Grafted Blade Greatsword' },
  { game: 'Elden Ring', type: 'weapon', name: 'Maliketh\'s Black Blade' },
  { game: 'Elden Ring', type: 'weapon', name: 'Golden Order Greatsword' },
  { game: 'Elden Ring', type: 'weapon', name: 'Godslayer\'s Greatsword' },
  { game: 'Elden Ring', type: 'weapon', name: 'Eclipse Shotel' },
  { game: 'Elden Ring', type: 'weapon', name: 'Sword of Night and Flame' },
  { game: 'Elden Ring', type: 'weapon', name: 'Ruins Greatsword' },
  { game: 'Elden Ring', type: 'weapon', name: 'Morgott\'s Cursed Sword' },
  { game: 'Elden Ring', type: 'weapon', name: 'Malenia\'s Blade' },
  { game: 'Elden Ring', type: 'weapon', name: 'Hand of Malenia' },
  { game: 'Elden Ring', type: 'weapon', name: 'Rotten Greataxe' },
  { game: 'Elden Ring', type: 'weapon', name: 'Giant-Crusher' },
  { game: 'Elden Ring', type: 'weapon', name: 'Mohgwyn\'s Sacred Spear' },
  { game: 'Elden Ring', type: 'weapon', name: 'Rykard\'s Rancor' },
  { game: 'Elden Ring', type: 'weapon', name: 'Eleonora\'s Poleblade' },
  { game: 'Elden Ring', type: 'weapon', name: 'Reduvia' },
  { game: 'Elden Ring', type: 'weapon', name: 'Bloodhound\'s Fang' },
  { game: 'Elden Ring', type: 'weapon', name: 'Winged Scythe' },
  { game: 'Elden Ring', type: 'weapon', name: 'Death\'s Poker' },
  { game: 'Elden Ring', type: 'weapon', name: 'Marais Executioner\'s Sword' },
  { game: 'Elden Ring', type: 'shield', name: 'Erdtree Greatshield' },
  { game: 'Elden Ring', type: 'shield', name: 'Fingerprint Stone Shield' },
  { game: 'Elden Ring', type: 'shield', name: 'Brass Shield' },
  { game: 'Elden Ring', type: 'armor', name: 'Radahn\'s Helm' },
  { game: 'Elden Ring', type: 'armor', name: 'Radahn\'s Lion Armor' },
  { game: 'Elden Ring', type: 'armor', name: 'Radahn\'s Gauntlets' },
  { game: 'Elden Ring', type: 'armor', name: 'Radahn\'s Greaves' },
  { game: 'Elden Ring', type: 'armor', name: 'Malenia\'s Helm' },
  { game: 'Elden Ring', type: 'armor', name: 'Malenia\'s Armor' },
  { game: 'Elden Ring', type: 'armor', name: 'Malenia\'s Gauntlet' },
  { game: 'Elden Ring', type: 'armor', name: 'Malenia\'s Greaves' },
  { game: 'Elden Ring', type: 'consumable', name: 'Smithing Stone (1)' },
  { game: 'Elden Ring', type: 'consumable', name: 'Smithing Stone (2)' },
  { game: 'Elden Ring', type: 'consumable', name: 'Smithing Stone (3)' },
  { game: 'Elden Ring', type: 'consumable', name: 'Smithing Stone (4)' },
  { game: 'Elden Ring', type: 'consumable', name: 'Smithing Stone (5)' },
  { game: 'Elden Ring', type: 'consumable', name: 'Smithing Stone (6)' },
  { game: 'Elden Ring', type: 'consumable', name: 'Smithing Stone (7)' },
  { game: 'Elden Ring', type: 'consumable', name: 'Smithing Stone (8)' },
  { game: 'Elden Ring', type: 'consumable', name: 'Ancient Dragon Smithing Stone' },
  { game: 'Elden Ring', type: 'consumable', name: 'Somber Smithing Stone (1)' },
  { game: 'Elden Ring', type: 'consumable', name: 'Somber Smithing Stone (2)' },
  { game: 'Elden Ring', type: 'consumable', name: 'Somber Smithing Stone (3)' },
  { game: 'Elden Ring', type: 'consumable', name: 'Somber Smithing Stone (4)' },
  { game: 'Elden Ring', type: 'consumable', name: 'Somber Smithing Stone (5)' },
  { game: 'Elden Ring', type: 'consumable', name: 'Somber Smithing Stone (6)' },
  { game: 'Elden Ring', type: 'consumable', name: 'Somber Smithing Stone (7)' },
  { game: 'Elden Ring', type: 'consumable', name: 'Somber Smithing Stone (8)' },
  { game: 'Elden Ring', type: 'consumable', name: 'Somber Ancient Dragon Smithing Stone' },
  { game: 'Elden Ring', type: 'consumable', name: 'Golden Seed' },
  { game: 'Elden Ring', type: 'consumable', name: 'Sacred Tear' },
  { game: 'Elden Ring', type: 'ring', name: 'Erdtree\'s Favor' },
  { game: 'Elden Ring', type: 'ring', name: 'Radagon\'s Soreseal' },
  { game: 'Elden Ring', type: 'ring', name: 'Godfrey Icon' },
  { game: 'Elden Ring', type: 'ring', name: 'Shard of Alexander' },
  { game: 'Elden Ring', type: 'ring', name: 'Millicent\'s Prosthesis' },
  { game: 'Elden Ring', type: 'ring', name: 'Rotten Winged Sword Insignia' },
  { game: 'Elden Ring', type: 'ring', name: 'Dragoncrest Greatshield Talisman' },

  // ═══════════════════════════════════════════
  //  DEMON'S SOULS
  // ═══════════════════════════════════════════

  { game: "Demon's Souls", type: 'weapon', name: 'Demonbrandt' },
  { game: "Demon's Souls", type: 'weapon', name: 'Soulbrandt' },
  { game: "Demon's Souls", type: 'weapon', name: 'Northern Regalia' },
  { game: "Demon's Souls", type: 'weapon', name: 'Blueblood Sword' },
  { game: "Demon's Souls", type: 'weapon', name: 'Morion Blade' },
  { game: "Demon's Souls", type: 'weapon', name: 'Meat Cleaver' },
  { game: "Demon's Souls", type: 'weapon', name: 'Dragon Bone Smasher' },
  { game: "Demon's Souls", type: 'weapon', name: 'Scraping Spear' },
  { game: "Demon's Souls", type: 'weapon', name: 'Kilij' },
  { game: "Demon's Souls", type: 'weapon', name: 'Crescent Falchion' },
  { game: "Demon's Souls", type: 'weapon', name: 'Magic Sword "Makoto"' },
  { game: "Demon's Souls", type: 'weapon', name: 'Istarelle' },
  { game: "Demon's Souls", type: 'weapon', name: 'Lava Bow' },
  { game: "Demon's Souls", type: 'shield', name: 'Dark Silver Shield' },
  { game: "Demon's Souls", type: 'shield', name: 'Adjudicator\'s Shield' },
  { game: "Demon's Souls", type: 'shield', name: 'Brushwood Shield' },
  { game: "Demon's Souls", type: 'consumable', name: 'Colorless Demon\'s Soul' },
  { game: "Demon's Souls", type: 'consumable', name: 'Pure Moonlightstone' },
  { game: "Demon's Souls", type: 'consumable', name: 'Pure Bladestone' },
  { game: "Demon's Souls", type: 'consumable', name: 'Pure Clearstone' },
  { game: "Demon's Souls", type: 'consumable', name: 'Pure Dragonstone' },
  { game: "Demon's Souls", type: 'consumable', name: 'Pure Faintstone' },
  { game: "Demon's Souls", type: 'consumable', name: 'Pure Greystone' },
  { game: "Demon's Souls", type: 'consumable', name: 'Pure Hardstone' },
  { game: "Demon's Souls", type: 'consumable', name: 'Pure Marrowstone' },
  { game: "Demon's Souls", type: 'consumable', name: 'Pure Sharpstone' },
  { game: "Demon's Souls", type: 'consumable', name: 'Pure Suckerstone' },
  { game: "Demon's Souls", type: 'consumable', name: 'Spiderstone' },
  { game: "Demon's Souls", type: 'consumable', name: 'Darkmoonstone' },
  { game: "Demon's Souls", type: 'ring', name: 'Clever Rat\'s Ring' },
  { game: "Demon's Souls", type: 'ring', name: 'Cling Ring' },
  { game: "Demon's Souls", type: 'ring', name: 'Eternal Warrior\'s Ring' },
  { game: "Demon's Souls", type: 'ring', name: 'Friend\'s Ring' },
  { game: "Demon's Souls", type: 'ring', name: 'Foe\'s Ring' },
  { game: "Demon's Souls", type: 'ring', name: 'Ring of Avarice' },
  { game: "Demon's Souls", type: 'ring', name: 'Ring of the Accursed' },
];

(async () => {
  try {
    await sequelize.authenticate();
    console.log('Connected to database.\n');

    // Sync to ensure table exists
    await sequelize.sync({ alter: true });

    let created = 0;
    let skipped = 0;

    for (const item of ITEMS) {
      const [, wasCreated] = await Item.findOrCreate({
        where: { name: item.name, game: item.game },
        defaults: { ...item, iconPath: null },
      });
      if (wasCreated) created++;
      else skipped++;
    }

    console.log(`✅  Seed complete.`);
    console.log(`    Created : ${created} items`);
    console.log(`    Skipped : ${skipped} (already existed)`);
    console.log(`    Total   : ${ITEMS.length} items across all games`);
    process.exit(0);
  } catch (err) {
    console.error('❌  Seed failed:', err.message);
    process.exit(1);
  }
})();
